version: "3.9"
services:
  golang_api_server:
    build:
      context: "./server"
      dockerfile: "./Dockerfile"
    restart: on-failure
    volumes: 
      - "./ferryf_FS:/var/ferryf_FS"

  # We can use remote DB for now
  # db:
  #   image: postgres:12
  #   restart: always
  #   environment:
  #     POSTGRES_USER: example
  #     POSTGRES_PASSWORD: example

  nginx:
    build: 
      context: "."
      dockerfile: "./Dockerfile-build"
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - "./ferryf_FS:/var/ferryf_FS"